import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:flutter_downloader/flutter_downloader.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'firebase_options.dart'; // This file will be generated by flutterfire CLI
import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show kIsWeb;

import 'screens/history_screen.dart';
import 'screens/settings_screen.dart';
import 'screens/download_screen.dart';
import 'services/settings_service.dart';
import 'services/widget_service.dart';
import 'services/quick_actions_service.dart';
import 'utils/platform_detector.dart';
import 'services/api_service.dart';
import 'services/download_service.dart';
import 'services/history_service.dart';
import 'models/tiktok_model.dart';
import 'models/instagram_model.dart';
import 'models/facebook_model.dart';
import 'models/spotify_model.dart';
import 'models/youtube_model.dart';
import 'models/twitter_model.dart';
import 'models/threads_model.dart';
import 'widgets/ads/adblock_guard.dart';
import 'services/ad_manager.dart';

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize FlutterDownloader y Ads (Mobile Only)
  if (!kIsWeb && (Platform.isAndroid || Platform.isIOS)) {
    await FlutterDownloader.initialize(
      debug: true, // Optional: set to false to disable printing logs to console
      ignoreSsl:
          true, // Option: set to false to disable working with http links
    );
    await MobileAds.instance.initialize();
  }

  // Initialize Firebase
  try {
    await initFirebase();
  } catch (e) {
    debugPrint('Firebase initialization error: $e');
  }

  // Initialize date formatting for Spanish locale
  await initializeDateFormatting('es', null);

  // Initialize widget service (mobile only)
  if (WidgetService.isSupported) {
    await WidgetService.initialize();
  }

  // Allow all orientations to support tablet and desktop landscape layouts
  // SystemChrome.setPreferredOrientations is intentionally removed.

  // Prevent tree-shaking of background entry point
  if (DateTime.now().year < 2000) {
    backgroundMain();
  }

  runApp(const DownloaderApp());
}

class DownloaderApp extends StatefulWidget {
  const DownloaderApp({super.key});

  @override
  State<DownloaderApp> createState() => DownloaderAppState();
}

class DownloaderAppState extends State<DownloaderApp>
    with WidgetsBindingObserver {
  ThemeMode _themeMode = ThemeMode.system;

  final QuickActionsService _quickActions = QuickActionsService();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    AdManager.loadAppOpenAd(); // Load initial AppOpenAd
    _loadThemeMode();
    _setupWidgetListener();
    _setupQuickActions();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      AdManager.showAppOpenAdIfAvailable();
    }
  }

  void _setupQuickActions() {
    _quickActions.initialize(context, (action) {
      if (action == 'action_history') {
        navigatorKey.currentState?.push(
          MaterialPageRoute(builder: (_) => const HistoryScreen()),
        );
      } else if (action == 'action_settings') {
        navigatorKey.currentState?.push(
          MaterialPageRoute(builder: (_) => const SettingsScreen()),
        );
      }
    });
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _quickActions.dispose();
    super.dispose();
  }

  void _setupWidgetListener() {
    WidgetService.onActionReceived = (action, url) {
      if (action.contains('OPEN_HISTORY')) {
        navigatorKey.currentState?.push(
          MaterialPageRoute(builder: (_) => const HistoryScreen()),
        );
      } else if (action.contains('OPEN_SETTINGS')) {
        navigatorKey.currentState?.push(
          MaterialPageRoute(builder: (_) => const SettingsScreen()),
        );
      } else if (action.contains('DOWNLOAD_FROM_WIDGET')) {
        // Redirigir a la pantalla de descarga
        navigatorKey.currentState?.popUntil((route) => route.isFirst);
        if (url != null && url.isNotEmpty) {
          // Si hay una URL en el portapapeles, la pasamos
          // (Podemos extender DownloadScreen para recibir una URL inicial)
          Navigator.pushReplacement(
            navigatorKey.currentContext!,
            MaterialPageRoute(builder: (_) => DownloadScreen(initialUrl: url)),
          );
        }
      }
    };
  }

  Future<void> _loadThemeMode() async {
    final mode = await SettingsService.getThemeMode();
    setState(() => _themeMode = mode);
  }

  void updateThemeMode(ThemeMode mode) {
    setState(() => _themeMode = mode);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Media Keep',
      theme: ThemeData(
        brightness: Brightness.light,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF4CC9F0),
          brightness: Brightness.light,
          primary: const Color(0xFF00B4D8),
          secondary: const Color(0xFF48CAE4),
          surface: Colors.white,
          onSurface: const Color(0xFF18181B),
        ),
        useMaterial3: true,
        scaffoldBackgroundColor: Colors.white,
        textTheme: GoogleFonts.outfitTextTheme(ThemeData.light().textTheme),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.transparent,
          elevation: 0,
          centerTitle: true,
          scrolledUnderElevation: 0,
          titleTextStyle: TextStyle(
            color: Color(0xFF18181B),
            fontSize: 22,
            fontWeight: FontWeight.bold,
          ),
          iconTheme: IconThemeData(color: Color(0xFF18181B)),
        ),
        cardTheme: CardThemeData(
          elevation: 0,
          margin: EdgeInsets.zero,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(24),
            side: BorderSide(
              color: const Color(0xFF00B4D8).withValues(alpha: 0.1),
            ),
          ),
          color: const Color(0xFFFAFAFA),
        ),
        filledButtonTheme: FilledButtonThemeData(
          style: FilledButton.styleFrom(
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16),
            ),
            backgroundColor: const Color(0xFF00B4D8),
            foregroundColor: Colors.white,
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: const Color(0xFFFAFAFA),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide.none,
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide(
              color: const Color(0xFF18181B).withValues(alpha: 0.05),
            ),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: const BorderSide(color: Color(0xFF00B4D8), width: 2),
          ),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 20,
            vertical: 18,
          ),
        ),
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF4CC9F0),
          brightness: Brightness.dark,
          surface: const Color(0xFF18181B),
          onSurface: const Color(0xFFE4E4E7),
        ),
        useMaterial3: true,
        scaffoldBackgroundColor: const Color(0xFF18181B),
        textTheme: GoogleFonts.outfitTextTheme(ThemeData.dark().textTheme),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.transparent,
          elevation: 0,
          centerTitle: true,
          scrolledUnderElevation: 0,
          titleTextStyle: TextStyle(
            color: Colors.white,
            fontSize: 22,
            fontWeight: FontWeight.bold,
          ),
          iconTheme: IconThemeData(color: Colors.white),
        ),
        cardTheme: CardThemeData(
          elevation: 0,
          margin: EdgeInsets.zero,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(24),
            side: BorderSide(color: Colors.white.withValues(alpha: 0.05)),
          ),
          color: const Color(0xFF27272A),
        ),
        filledButtonTheme: FilledButtonThemeData(
          style: FilledButton.styleFrom(
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16),
            ),
            backgroundColor: const Color(0xFF4CC9F0),
            foregroundColor: const Color(0xFF18181B),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: const Color(0xFF27272A),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide.none,
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide(color: Colors.white.withValues(alpha: 0.05)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: const BorderSide(color: Color(0xFF4CC9F0), width: 2),
          ),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 20,
            vertical: 18,
          ),
        ),
      ),
      themeMode: _themeMode,
      navigatorKey: navigatorKey,
      builder: (context, child) => AdBlockGuard(child: child!),
      home: const DownloadScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

// ==========================================
// BACKGROUND ENTRY POINT
// ==========================================

// Entry point for the background process
@pragma('vm:entry-point')
void backgroundMain() {
  // Ensure Flutter binding is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize the method channel for background communication
  const MethodChannel channel = MethodChannel('com.mediakeep.aur/background');

  // Set up the method call handler
  channel.setMethodCallHandler((MethodCall call) async {
    if (call.method == 'startDownload') {
      final String url = call.arguments as String;
      await _handleBackgroundDownload(url, channel);
    }
  });
}

Future<void> _handleBackgroundDownload(
  String url,
  MethodChannel channel,
) async {
  try {
    // 1. Detect platform
    final platform = PlatformDetector.detectPlatform(url);
    if (platform == null) {
      await channel.invokeMethod('downloadError', {
        'message': 'Plataforma no soportada',
      });
      return;
    }

    // NEW: Check if already downloaded
    final isDuplicate = await HistoryService.isContentAlreadyDownloaded(
      sourceUrl: url,
    );
    if (isDuplicate) {
      debugPrint('[Background] URL already downloaded: $url');
      await channel.invokeMethod('downloadError', {
        'message': 'Este contenido ya fue descargado previamente.',
      });
      return;
    }

    // 2. Fetch media info
    final response = await ApiService.fetchMedia(url: url, platform: platform);
    if (!response.success || response.data == null) {
      await channel.invokeMethod('downloadError', {
        'message': response.errorMessage ?? 'Error fetching media',
      });
      return;
    }

    // 3. Parse and Extract BEST Data
    String? downloadUrl;
    String title = 'media';
    String type = 'video';

    final parsedData = ApiService.parseResponseData(response.data!, platform);

    if (platform == 'tiktok' && parsedData is TikTokData) {
      title = parsedData.title;
      // TikTok MediaInfo properties are non-nullable in model but could be null at runtime if JSON missing?
      downloadUrl = parsedData.media.noWatermark?.hdPlay;

      if (downloadUrl == null || downloadUrl.isEmpty) {
        downloadUrl = parsedData.media.noWatermark?.play;
      }
      if (downloadUrl == null || downloadUrl.isEmpty) {
        downloadUrl = parsedData.media.watermark?.play;
      }

      type = 'video';
      if (parsedData.media.images.isNotEmpty &&
          (downloadUrl == null || downloadUrl.isEmpty)) {
        downloadUrl = parsedData.media.images.first;
        type = 'image';
      }
    } else if (platform == 'facebook' && parsedData is FacebookData) {
      title = parsedData.title;
      downloadUrl = parsedData.download;
      if (downloadUrl == null || downloadUrl.isEmpty) {
        downloadUrl = parsedData.url;
      }
      type = parsedData.type;
    } else if (platform == 'instagram' && parsedData is InstagramData) {
      if (parsedData.media.isNotEmpty) {
        final media = parsedData.media.first;
        downloadUrl = media.download;
        if ((downloadUrl == null || downloadUrl.isEmpty) &&
            media.options.isNotEmpty) {
          downloadUrl = media.options.first.url;
        }
        title = 'instagram_media';
        type = (downloadUrl != null && downloadUrl.contains('.jpg'))
            ? 'image'
            : 'video';
      }
    } else if (platform == 'youtube' && parsedData is YouTubeData) {
      title = parsedData.info.title ?? 'youtube_video';
      if (parsedData.videos.isNotEmpty) {
        // Find best quality or default to first
        downloadUrl = parsedData.videos.first.url;
      }
      type = 'video';
    } else if (platform == 'spotify' && parsedData is SpotifyData) {
      title = parsedData.title;
      downloadUrl = parsedData.download;
      type = 'audio';
    } else if (platform == 'twitter' && parsedData is TwitterData) {
      title = parsedData.title ?? 'twitter_media';
      if (parsedData.media != null && parsedData.media!.isNotEmpty) {
        final m = parsedData.media!.first;
        downloadUrl = m.url;
        type = m.type ?? 'video';
      }
    } else if (platform == 'threads' && parsedData is ThreadsData) {
      if (parsedData.media.isNotEmpty) {
        downloadUrl = parsedData.media.first.url;
        type = parsedData.media.first.type;
      }
    }

    // 4. Validate URL
    debugPrint('[Background] Extracted URL: $downloadUrl');

    if (downloadUrl == null || downloadUrl.isEmpty) {
      debugPrint('[Background] URL Extraction Failed!');
      await channel.invokeMethod('downloadError', {
        'message': 'No se pudo extraer el enlace de descarga.',
      });
      return;
    }

    // Update status BEFORE starting download
    String statusMsg =
        'Descargando $type de ${platform.substring(0, 1).toUpperCase()}${platform.substring(1)}...';
    await channel.invokeMethod('updateStatus', {'status': statusMsg});

    // 5. Start Download
    debugPrint('[Background] Starting DownloadService...');
    final result = await DownloadService.startDownload(
      url: downloadUrl,
      type: type,
      platform: platform,
      title: title,
      sourceUrl: url,
      onProgress: (progress, status) {},
    );

    if (result.success) {
      await channel.invokeMethod('downloadComplete', {
        'filename': result.fileName,
        'filepath': result.filePath,
        'title': title, // Send title for notification
      });
    } else {
      await channel.invokeMethod('downloadError', {
        'message': result.errorMessage ?? 'Download failed',
      });
    }
  } catch (e) {
    debugPrint("Background download error: $e");
    await channel.invokeMethod('downloadError', {'message': e.toString()});
  }
}
